package OperacionApp;


/**
* OperacionApp/_OperacionStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operacion.idl
* lunes 23 de mayo de 2022 11:52:33 AM CDT
*/

public class _OperacionStub extends org.omg.CORBA.portable.ObjectImpl implements OperacionApp.Operacion
{


  //operaciones (métodos)
  public String ejecutarOperacion (String nombre, int tam)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ejecutarOperacion", true);
                $out.write_string (nombre);
                $out.write_long (tam);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ejecutarOperacion (nombre, tam        );
            } finally {
                _releaseReply ($in);
            }
  } // ejecutarOperacion

  public void apagarConexion ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("apagarConexion", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                apagarConexion (        );
            } finally {
                _releaseReply ($in);
            }
  } // apagarConexion

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:OperacionApp/Operacion:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _OperacionStub
