package OperacionApp;


/**
* OperacionApp/Operacion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operacion.idl
* lunes 23 de mayo de 2022 11:52:33 AM CDT
*/

public interface Operacion extends OperacionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Operacion
