package OperacionApp;


/**
* OperacionApp/OperacionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operacion.idl
* lunes 23 de mayo de 2022 11:52:33 AM CDT
*/

abstract public class OperacionHelper
{
  private static String  _id = "IDL:OperacionApp/Operacion:1.0";

  public static void insert (org.omg.CORBA.Any a, OperacionApp.Operacion that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static OperacionApp.Operacion extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (OperacionApp.OperacionHelper.id (), "Operacion");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static OperacionApp.Operacion read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_OperacionStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, OperacionApp.Operacion value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static OperacionApp.Operacion narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OperacionApp.Operacion)
      return (OperacionApp.Operacion)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      OperacionApp._OperacionStub stub = new OperacionApp._OperacionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static OperacionApp.Operacion unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OperacionApp.Operacion)
      return (OperacionApp.Operacion)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      OperacionApp._OperacionStub stub = new OperacionApp._OperacionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
