package OperacionApp;


/**
* OperacionApp/OperacionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operacion.idl
* lunes 23 de mayo de 2022 11:52:33 AM CDT
*/

public interface OperacionOperations 
{

  //operaciones (métodos)
  String ejecutarOperacion (String nombre, int tam);
  void apagarConexion ();
} // interface OperacionOperations
