package OperacionApp;

/**
* OperacionApp/OperacionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operacion.idl
* lunes 23 de mayo de 2022 11:52:33 AM CDT
*/

public final class OperacionHolder implements org.omg.CORBA.portable.Streamable
{
  public OperacionApp.Operacion value = null;

  public OperacionHolder ()
  {
  }

  public OperacionHolder (OperacionApp.Operacion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OperacionApp.OperacionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OperacionApp.OperacionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OperacionApp.OperacionHelper.type ();
  }

}
